/*
 * Timeline events
 *
 * This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You'll find multiple use cases for this API in the sections below.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Crm.Timeline.Model;
using HubSpot.Crm.Timeline.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Crm.Timeline.Test.Model
{
    /// <summary>
    ///  Class for testing TimelineEventTemplateToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimelineEventTemplateTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimelineEventTemplateToken
        //private TimelineEventTemplateToken instance;

        public TimelineEventTemplateTokenTests()
        {
            // TODO uncomment below to create an instance of TimelineEventTemplateToken
            //instance = new TimelineEventTemplateToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimelineEventTemplateToken
        /// </summary>
        [Fact]
        public void TimelineEventTemplateTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimelineEventTemplateToken
            //Assert.IsType<TimelineEventTemplateToken>(instance);
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'ObjectPropertyName'
        /// </summary>
        [Fact]
        public void ObjectPropertyNameTest()
        {
            // TODO unit test for the property 'ObjectPropertyName'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
