/*
 * Companies
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HubSpot.Crm.Companies.Client;
using HubSpot.Crm.Companies.Api;
// uncomment below to import models
//using HubSpot.Crm.Companies.Model;

namespace HubSpot.Crm.Companies.Test.Api
{
    /// <summary>
    ///  Class for testing PublicObjectApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PublicObjectApiTests : IDisposable
    {
        private PublicObjectApi instance;

        public PublicObjectApiTests()
        {
            instance = new PublicObjectApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicObjectApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PublicObjectApi
            //Assert.IsType<PublicObjectApi>(instance);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsCompaniesMergeMerge
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsCompaniesMergeMergeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PublicMergeInput publicMergeInput = null;
            //var response = instance.PostCrmV3ObjectsCompaniesMergeMerge(publicMergeInput);
            //Assert.IsType<SimplePublicObject>(response);
        }
    }
}
