/*
 * CRM cards
 *
 * Allows an app to extend the CRM UI by surfacing custom cards in the sidebar of record pages. These cards are defined up-front as part of app configuration, then populated by external data fetch requests when the record page is accessed by a user.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Crm.CrmExtensions.Model;
using HubSpot.Crm.CrmExtensions.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Crm.CrmExtensions.Test.Model
{
    /// <summary>
    ///  Class for testing CardDisplayProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardDisplayPropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardDisplayProperty
        //private CardDisplayProperty instance;

        public CardDisplayPropertyTests()
        {
            // TODO uncomment below to create an instance of CardDisplayProperty
            //instance = new CardDisplayProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardDisplayProperty
        /// </summary>
        [Fact]
        public void CardDisplayPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardDisplayProperty
            //Assert.IsType<CardDisplayProperty>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
