/*
 * Subscriptions
 *
 * Subscriptions allow contacts to control what forms of communications they receive. Contacts can decide whether they want to receive communication pertaining to a specific topic, brand, or an entire HubSpot account.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.CommunicationPreferences.CommunicationsStatus.Model;
using HubSpot.CommunicationPreferences.CommunicationsStatus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.CommunicationPreferences.CommunicationsStatus.Test.Model
{
    /// <summary>
    ///  Class for testing PublicSubscriptionStatusesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicSubscriptionStatusesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicSubscriptionStatusesResponse
        //private PublicSubscriptionStatusesResponse instance;

        public PublicSubscriptionStatusesResponseTests()
        {
            // TODO uncomment below to create an instance of PublicSubscriptionStatusesResponse
            //instance = new PublicSubscriptionStatusesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicSubscriptionStatusesResponse
        /// </summary>
        [Fact]
        public void PublicSubscriptionStatusesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicSubscriptionStatusesResponse
            //Assert.IsType<PublicSubscriptionStatusesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Fact]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'SubscriptionStatuses'
        /// </summary>
        [Fact]
        public void SubscriptionStatusesTest()
        {
            // TODO unit test for the property 'SubscriptionStatuses'
        }

    }

}
