/*
 * Tickets
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HubSpot.Crm.Tickets.Client;
using HubSpot.Crm.Tickets.Api;
// uncomment below to import models
//using HubSpot.Crm.Tickets.Model;

namespace HubSpot.Crm.Tickets.Test.Api
{
    /// <summary>
    ///  Class for testing BasicApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BasicApiTests : IDisposable
    {
        private BasicApi instance;

        public BasicApiTests()
        {
            instance = new BasicApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasicApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BasicApi
            //Assert.IsType<BasicApi>(instance);
        }

        /// <summary>
        /// Test DeleteCrmV3ObjectsTicketsTicketIdArchive
        /// </summary>
        [Fact]
        public void DeleteCrmV3ObjectsTicketsTicketIdArchiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ticketId = null;
            //instance.DeleteCrmV3ObjectsTicketsTicketIdArchive(ticketId);
        }

        /// <summary>
        /// Test GetCrmV3ObjectsTicketsGetPage
        /// </summary>
        [Fact]
        public void GetCrmV3ObjectsTicketsGetPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string after = null;
            //List<string> properties = null;
            //List<string> propertiesWithHistory = null;
            //List<string> associations = null;
            //bool? archived = null;
            //var response = instance.GetCrmV3ObjectsTicketsGetPage(limit, after, properties, propertiesWithHistory, associations, archived);
            //Assert.IsType<CollectionResponseSimplePublicObjectWithAssociationsForwardPaging>(response);
        }

        /// <summary>
        /// Test GetCrmV3ObjectsTicketsTicketIdGetById
        /// </summary>
        [Fact]
        public void GetCrmV3ObjectsTicketsTicketIdGetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ticketId = null;
            //List<string> properties = null;
            //List<string> propertiesWithHistory = null;
            //List<string> associations = null;
            //bool? archived = null;
            //string idProperty = null;
            //var response = instance.GetCrmV3ObjectsTicketsTicketIdGetById(ticketId, properties, propertiesWithHistory, associations, archived, idProperty);
            //Assert.IsType<SimplePublicObjectWithAssociations>(response);
        }

        /// <summary>
        /// Test PatchCrmV3ObjectsTicketsTicketIdUpdate
        /// </summary>
        [Fact]
        public void PatchCrmV3ObjectsTicketsTicketIdUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ticketId = null;
            //SimplePublicObjectInput simplePublicObjectInput = null;
            //string idProperty = null;
            //var response = instance.PatchCrmV3ObjectsTicketsTicketIdUpdate(ticketId, simplePublicObjectInput, idProperty);
            //Assert.IsType<SimplePublicObject>(response);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsTicketsCreate
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsTicketsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SimplePublicObjectInputForCreate simplePublicObjectInputForCreate = null;
            //var response = instance.PostCrmV3ObjectsTicketsCreate(simplePublicObjectInputForCreate);
            //Assert.IsType<SimplePublicObject>(response);
        }
    }
}
