/*
 * Accounting Extension
 *
 * These APIs allow you to interact with HubSpot's Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot 
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Crm.Accounting.Model;
using HubSpot.Crm.Accounting.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Crm.Accounting.Test.Model
{
    /// <summary>
    ///  Class for testing ExchangeRateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExchangeRateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExchangeRateResponse
        //private ExchangeRateResponse instance;

        public ExchangeRateResponseTests()
        {
            // TODO uncomment below to create an instance of ExchangeRateResponse
            //instance = new ExchangeRateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExchangeRateResponse
        /// </summary>
        [Fact]
        public void ExchangeRateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExchangeRateResponse
            //Assert.IsType<ExchangeRateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Fact]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'SourceCurrencyCode'
        /// </summary>
        [Fact]
        public void SourceCurrencyCodeTest()
        {
            // TODO unit test for the property 'SourceCurrencyCode'
        }
        /// <summary>
        /// Test the property 'TargetCurrencyCode'
        /// </summary>
        [Fact]
        public void TargetCurrencyCodeTest()
        {
            // TODO unit test for the property 'TargetCurrencyCode'
        }

    }

}
