/*
 * CrmPublicAssociationsServiceV4
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Crm.CrmAssociations.Model;
using HubSpot.Crm.CrmAssociations.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Crm.CrmAssociations.Test.Model
{
    /// <summary>
    ///  Class for testing BatchResponsePublicAssociationMultiWithLabelWithErrors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchResponsePublicAssociationMultiWithLabelWithErrorsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchResponsePublicAssociationMultiWithLabelWithErrors
        //private BatchResponsePublicAssociationMultiWithLabelWithErrors instance;

        public BatchResponsePublicAssociationMultiWithLabelWithErrorsTests()
        {
            // TODO uncomment below to create an instance of BatchResponsePublicAssociationMultiWithLabelWithErrors
            //instance = new BatchResponsePublicAssociationMultiWithLabelWithErrors();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchResponsePublicAssociationMultiWithLabelWithErrors
        /// </summary>
        [Fact]
        public void BatchResponsePublicAssociationMultiWithLabelWithErrorsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchResponsePublicAssociationMultiWithLabelWithErrors
            //Assert.IsType<BatchResponsePublicAssociationMultiWithLabelWithErrors>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'NumErrors'
        /// </summary>
        [Fact]
        public void NumErrorsTest()
        {
            // TODO unit test for the property 'NumErrors'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'RequestedAt'
        /// </summary>
        [Fact]
        public void RequestedAtTest()
        {
            // TODO unit test for the property 'RequestedAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
