/*
 * CrmPublicAssociationsServiceV4
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Crm.CrmAssociations.Model;
using HubSpot.Crm.CrmAssociations.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Crm.CrmAssociations.Test.Model
{
    /// <summary>
    ///  Class for testing PublicAssociationMultiWithLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicAssociationMultiWithLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicAssociationMultiWithLabel
        //private PublicAssociationMultiWithLabel instance;

        public PublicAssociationMultiWithLabelTests()
        {
            // TODO uncomment below to create an instance of PublicAssociationMultiWithLabel
            //instance = new PublicAssociationMultiWithLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicAssociationMultiWithLabel
        /// </summary>
        [Fact]
        public void PublicAssociationMultiWithLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicAssociationMultiWithLabel
            //Assert.IsType<PublicAssociationMultiWithLabel>(instance);
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Paging'
        /// </summary>
        [Fact]
        public void PagingTest()
        {
            // TODO unit test for the property 'Paging'
        }

    }

}
