/*
 * Marketing Events Extension
 *
 * These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to: * Create, Read or update Marketing Event information in HubSpot * Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event. * Specify a URL that can be called to get the details of a Marketing Event. 
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.Marketing.MarketingEventsBeta.Model;
using HubSpot.Marketing.MarketingEventsBeta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.Marketing.MarketingEventsBeta.Test.Model
{
    /// <summary>
    ///  Class for testing BatchResponseSubscriberEmailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchResponseSubscriberEmailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchResponseSubscriberEmailResponse
        //private BatchResponseSubscriberEmailResponse instance;

        public BatchResponseSubscriberEmailResponseTests()
        {
            // TODO uncomment below to create an instance of BatchResponseSubscriberEmailResponse
            //instance = new BatchResponseSubscriberEmailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchResponseSubscriberEmailResponse
        /// </summary>
        [Fact]
        public void BatchResponseSubscriberEmailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchResponseSubscriberEmailResponse
            //Assert.IsType<BatchResponseSubscriberEmailResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'NumErrors'
        /// </summary>
        [Fact]
        public void NumErrorsTest()
        {
            // TODO unit test for the property 'NumErrors'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'RequestedAt'
        /// </summary>
        [Fact]
        public void RequestedAtTest()
        {
            // TODO unit test for the property 'RequestedAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
